swagger: "2.0"
info:
  title: Core App
  description: Handles core requests for the app
  version: '1.0.0'
host: 'amurse.appspot.com'
basePath: '/api'
schemes:
  - "https"
paths:
  /getMessages:
    post:
      description: 'get messages for a specific conversation'
      operationId: 'getMessages'
      responses:
        200:
          description: 'Success'
          schema:
            type: string
        400:
          description: 'Something went wrong'
  /getConversations:
    post:
      description: 'returns all conversations for a particular user'
      operationId: 'getConversations'
      responses:
        200:
          description: 'Success'
          schema:
            type: string
        400:
          description: 'Something went wrong'
  '/getConversation':
    post:
      description: 'returns content for a specific conversation'
      operationId: 'getConversation'
      responses:
        200:
          description: 'Success'
          schema:
            type: string
        400:
          description: 'Something went wrong'
  '/createConversation':
    post:
      description: 'creates a new conversation between 2 wallet addresses'
      operationId: 'createConversation'
      responses:
        200:
          description: 'Success'
          schema:
            type: string
        400:
          description: 'Something went wrong'
  '/exists':
    post:
      description: 'returns if conversation with particular id exists'
      operationId: 'exists'
      responses:
        200:
          description: 'Success'
          schema:
            type: string
        400:
          description: 'Something went wrong'
  '/getSessions':
    post:
      description: 'returns the number of active sessions'
      operationId: 'getSessions'
      responses:
        200:
          description: 'Success'
          schema:
            type: string
        400:
          description: 'Something went wrong'
  '/loginValidate':
    post:
      description: 'logins the user based on if session already exists'
      operationId: 'loginValidate'
      responses:
        200:
          description: 'Success'
          schema:
            type: string
        400:
          description: 'Something went wrong'
  '/login':
    post:
      description: 'logs in the user if there is no session'
      operationId: 'login'
      responses:
        200:
          description: 'Success'
          schema:
            type: string
        400:
          description: 'Something went wrong'
  
    




